name: Node.js CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm run build

      - name: Depoly
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.VPS_ADDR }}
          private_key: ${{ secrets.VPS_KEY }}
          username: ${{ secrets.VPS_USR }}
          port: ${{ secrets.VPS_PORT }}
          scp_source: "build"
          scp_target: "~/errWeb/"
          before_script: rm -rf ~/errWeb/*
          after_script: |
            sudo -S service err-web restart<< EOF
            ${{ secrets.VPS_PWD }}
            EOF

